### ISSUE TITLE
How to achieve independent parallel scopes or hierarchical scopes?

### ISSUE THREAD

**Issue by Ne0n11** [MelbourneDeveloper/ioc_container#7]
Hello, I was curious if this package can help in achieving such a thing. 

Hierarchy
Like for example - we have app wide scope, where we put our dependecies and then lower in the tree we create another scoped container just for one screen, let's say. And for this container we again say, what dependecies it include, and these dependecies might be the same type, as available in app wide container.

So like in that scope, you can get your scoped dependecies. And also if you try to get some dependency and it is not registered in scoped container so it would look in app wide container for it.

Parallel 
Another situation, when for example we have two screens at same time showing, like half of screen each. And those screens have their own container, with let's say, same repository type in it, but completely separate singleton instances.

**Comment by MelbourneDeveloper** [comment]
Hi @Ne0n11 . Good questions. Sorry I missed this issue. 

The first thing to note is that ioc_container is designed so that two instances are totally separate. There are no global declarations tucked away that could bring things unstuck. If you want to create a new, cloned container (scope) with no shared singletons, you can do that anywhere like this:

```
final scope = container.scoped(useExistingSingletons: false);
```
### Parallel
> when for example we have two screens at same time showing, like half of screen each. And those screens have their own container, with let's say, same repository type in it, but completely separate singleton instances.

You can have multiple containers anywhere in your app for parallel screens if you need them. However, scoping is generally not necessary. The normal use case is to use transient dependencies and hold on to them inside your `ChangeNotifier`, `StatefulWidget`, `Cubit`, or other state objects. Scoping is only necessary when you need to dispose of dependencies at the end. It's a special case. If you are using something like BloC, I would use the library's widgets to dispose of stream subscriptions automatically and so on.

### Hierarchy
> So like in that scope, you can get your scoped dependecies. And also if you try to get some dependency and it is not registered in scoped container so it would look in app wide container for it.

This sounds very much like what I am building in [flutter_ioc_container](https://pub.dev/packages/flutter_ioc_container). This is a set of Flutter extensions to expose the container from within the widget tree. I've been using this in an app I'm working on and waiting to see if there are any kinks. So far, there are no kinks. I will write some more documentation about this pretty soon. Here is an [example](https://github.com/MelbourneDeveloper/flutter_ioc_container/blob/main/example/lib/main.dart) of how it works.

![image](https://user-images.githubusercontent.com/16697547/200948963-148c3417-fceb-425d-872a-5e4e6fd8d901.png)

> it is not registered in scoped container so it would look in app wide container for it.

This specific feature does not exist yet, but, scopes are the corner case, not the normal scenario. The ideal app would only need one container throughout the widget tree. The container supports async initialization so it's perfectly normal to await getting dependencies so you can do initialization before getting them.

**Comment by MelbourneDeveloper** [comment]
@Ne0n11 is there any chance I could get in contact with you to discuss this issue? I'd like to talk through your use case.

**Comment by MelbourneDeveloper** [comment]
@Ne0n11 this PR #9 adds fallback resolution. This means you can maintain multiple scoped containers and fallback on existing instances higher in the hierarchy.

It addresses

> if you try to get some dependency and it is not registered in scoped container so it would look in app wide container for it.

**Comment by Ne0n11** [comment]
Hello, thanks for you work, I will check it out when I'll have time. For now closing as complete
